version: '3.8'

services:
  nginx-reverse-proxy:
    env_file:
      - project.env
    image: tuiteraz/nginx-reverse-proxy:1.0
    restart: unless-stopped
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-config:/etc/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"