version: '3'

services:
  nrp:
    env_file:
      - project.env
    environment:
      - TZ=Europe/Madrid
      - CERTBOT_WAIT=false
    image: tuiteraz/nginx-reverse-proxy:${LATEST_VERSION}
    platform: linux/aarch64 # m1/m2 mac
    restart: unless-stopped
    container_name: nrp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nrp.yaml:/etc/nrp.yaml
      - letsencrypt1:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      # - ./configs/nginx:/etc/nginx
    networks:
      multi-proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  dnsmasq:
    env_file:
      - project.env
    image: 4km3/dnsmasq:2.85-r2
    platform: linux/aarch64 # m1/m2 mac
    container_name: dnsmasq
    volumes:
      - ./configs/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      multi-proxy:
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  squid:
    env_file:
      - project.env
    image: tuiteraz/squid:5.9.0-1
    platform: linux/aarch64 # m1/m2 mac
    container_name: squid
    user: root
    volumes:
      - ./configs/squid/squid.conf:/etc/squid/squid.conf
    networks:
      multi-proxy:
    ports:
      - ${SQUID_PORT}:${SQUID_PORT}
    depends_on: 
      - dnsmasq
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  cadvisor:
    env_file:
      - project.env
    image: tuiteraz/cadvisor:0.47.2
    platform: linux/aarch64 # m1/m2 mac
    devices:
      - /dev/kmsg:/dev/kmsg
    container_name: cadvisor
    privileged: true
    ports:
      - 4082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro # for docker socket
      - /var/folders:/var/lib/docker:ro # directory, which contains Docker's data
      - /dev/disk0:/dev/disk # This directory, where disk I/O stats are available: diskutil list
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    networks:
      multi-proxy:
    restart: unless-stopped

networks:
  multi-proxy:
    driver: bridge

volumes:
  letsencrypt:
  letsencrypt1: