version: '3.8'

services:
  nginx-reverse-proxy:
    env_file:
      - project.env
    environment:
      - TZ=Europe/Madrid
    image: tuiteraz/nginx-reverse-proxy:0.1.1
    restart: unless-stopped
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nrp.yaml:/etc/nrp.yaml
      - letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      # - ./nginx-config:/etc/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  letsencrypt: