name: Build Docker image and push to Docker Hub

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sudo snap install yq
      - run: make create-docker-container-builder
      - run: make docker-build-n-push
      - run: docker logout
